server {
    listen 80;
    server_name localhost;
    root /usr/share/nginx/html;
    index index.html;

    location /norm-type/ {
        proxy_pass http://backend:3000/api/norm-type/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /entity-type/ {
        proxy_pass http://backend:3000/api/entity-type/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /entity/ {
        proxy_pass http://backend:3000/api/entity/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /theme/ {
        proxy_pass http://backend:3000/api/theme/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /subtheme/ {
        proxy_pass http://backend:3000/api/subtheme/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
